// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as clause$0 from "../clause/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as reflect$0 from "../../../reflect/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sync$0 from "../../../sync/models.js";

/**
 * DataType GORM data type
 */
export enum DataType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * GORM fields types
     */
    Bool = "bool",
    Int = "int",
    Uint = "uint",
    Float = "float",
    String = "string",
    Time = "time",
    Bytes = "bytes",
};

/**
 * Field is the representation of model schema's field
 */
export interface Field {
    "Name": string;
    "DBName": string;
    "BindNames": string[] | null;
    "EmbeddedBindNames": string[] | null;
    "DataType": DataType;
    "GORMDataType": DataType;
    "PrimaryKey": boolean;
    "AutoIncrement": boolean;
    "AutoIncrementIncrement": number;
    "Creatable": boolean;
    "Updatable": boolean;
    "Readable": boolean;
    "AutoCreateTime": TimeType;
    "AutoUpdateTime": TimeType;
    "HasDefaultValue": boolean;
    "DefaultValue": string;
    "DefaultValueInterface": any;
    "NotNull": boolean;
    "Unique": boolean;
    "Comment": string;
    "Size": number;
    "Precision": number;
    "Scale": number;
    "IgnoreMigration": boolean;
    "FieldType": reflect$0.Type;
    "IndirectFieldType": reflect$0.Type;
    "StructField": reflect$0.StructField;
    "Tag": reflect$0.StructTag;
    "TagSettings": { [_ in string]?: string } | null;
    "Schema": Schema | null;
    "EmbeddedSchema": Schema | null;
    "OwnerSchema": Schema | null;
    "ReflectValueOf": any;
    "ValueOf": any;
    "Set": any;
    "Serializer": SerializerInterface;
    "NewValuePool": FieldNewValuePool;

    /**
     * In some db (e.g. MySQL), Unique and UniqueIndex are indistinguishable.
     * When a column has a (not Mul) UniqueIndex, Migrator always reports its gorm.ColumnType is Unique.
     * It causes field unnecessarily migration.
     * Therefore, we need to record the UniqueIndex on this column (exclude Mul UniqueIndex) for MigrateColumnUnique.
     */
    "UniqueIndex": string;
}

/**
 * FieldNewValuePool field new scan value pool
 */
export type FieldNewValuePool = any;

/**
 * Namer namer interface
 */
export type Namer = any;

export interface Polymorphic {
    "PolymorphicID": Field | null;
    "PolymorphicType": Field | null;
    "Value": string;
}

export interface Reference {
    "PrimaryKey": Field | null;
    "PrimaryValue": string;
    "ForeignKey": Field | null;
    "OwnPrimaryKey": boolean;
}

export interface Relationship {
    "Name": string;
    "Type": RelationshipType;
    "Field": Field | null;
    "Polymorphic": Polymorphic | null;
    "References": (Reference | null)[] | null;
    "Schema": Schema | null;
    "FieldSchema": Schema | null;
    "JoinTable": Schema | null;
}

/**
 * RelationshipType relationship type
 */
export enum RelationshipType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * HasOneRel has one relationship
     */
    HasOne = "has_one",

    /**
     * HasManyRel has many relationship
     */
    HasMany = "has_many",

    /**
     * BelongsToRel belongs to relationship
     */
    BelongsTo = "belongs_to",

    /**
     * Many2ManyRel many to many relationship
     */
    Many2Many = "many_to_many",
    has = "has",
};

export interface Relationships {
    "HasOne": (Relationship | null)[] | null;
    "BelongsTo": (Relationship | null)[] | null;
    "HasMany": (Relationship | null)[] | null;
    "Many2Many": (Relationship | null)[] | null;
    "Relations": { [_ in string]?: Relationship | null } | null;
    "EmbeddedRelations": { [_ in string]?: Relationships | null } | null;
    "Mux": sync$0.RWMutex;
}

export interface Schema {
    "Name": string;
    "ModelType": reflect$0.Type;
    "Table": string;
    "PrioritizedPrimaryField": Field | null;
    "DBNames": string[] | null;
    "PrimaryFields": (Field | null)[] | null;
    "PrimaryFieldDBNames": string[] | null;
    "Fields": (Field | null)[] | null;
    "FieldsByName": { [_ in string]?: Field | null } | null;

    /**
     * embedded fields is 'Embed.Field'
     */
    "FieldsByBindName": { [_ in string]?: Field | null } | null;
    "FieldsByDBName": { [_ in string]?: Field | null } | null;

    /**
     * fields with default value assigned by database
     */
    "FieldsWithDefaultDBValue": (Field | null)[] | null;
    "Relationships": Relationships;
    "CreateClauses": clause$0.Interface[] | null;
    "QueryClauses": clause$0.Interface[] | null;
    "UpdateClauses": clause$0.Interface[] | null;
    "DeleteClauses": clause$0.Interface[] | null;
    "BeforeCreate": boolean;
    "AfterCreate": boolean;
    "BeforeUpdate": boolean;
    "AfterUpdate": boolean;
    "BeforeDelete": boolean;
    "AfterDelete": boolean;
    "BeforeSave": boolean;
    "AfterSave": boolean;
    "AfterFind": boolean;
}

/**
 * SerializerInterface serializer interface
 */
export type SerializerInterface = any;

/**
 * TimeType GORM time type
 */
export enum TimeType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * GORM time types
     */
    UnixTime = 1,
    UnixSecond = 2,
    UnixMillisecond = 3,
    UnixNanosecond = 4,
};
