// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TrayService 负责创建并维护系统托盘图标与菜单。
 * 
 * 从本版本起,托盘不再是"可切换的运行模式",而是应用的常驻入口:
 *   - 应用启动时由 app 层调用一次 Install,创建托盘图标 / 菜单;
 *   - 窗口关闭按钮被拦截为"隐藏",保证再次通过托盘唤出;
 *   - 前端仍可通过 ShowWindow 主动唤出主窗口。
 * 
 * TrayService 不直接依赖 window 包,主窗口通过 SetWindow 由 app 层注入,
 * 避免 services -> window 的循环依赖。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * Install 创建托盘图标与菜单,并注册窗口关闭拦截钩子。
 * 由 app 层在启动阶段调用一次;幂等:重复调用不会重复创建。
 */
export function Install(): $CancellablePromise<void> {
    return $Call.ByID(368717709);
}

/**
 * SetApp 由 app 层注入 Wails application 引用。
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3346475141, app);
}

/**
 * SetIcon 允许 app 层注入托盘图标数据(PNG 字节)。
 * 非 darwin 平台使用普通图标,darwin 使用 template 图标。
 * 未调用时使用 Wails 内置默认图标。
 */
export function SetIcon(data: string | null): $CancellablePromise<void> {
    return $Call.ByID(1439160171, data);
}

/**
 * SetWindow 由 app 层注入主窗口引用。
 */
export function SetWindow(win: application$0.WebviewWindow | null): $CancellablePromise<void> {
    return $Call.ByID(1138024530, win);
}

/**
 * ShowWindow 主动显示并聚焦主窗口(供前端 / 托盘菜单唤出窗口)。
 */
export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(4014144003);
}
