// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExtractResult 是骨架提取的返回结构。
 * Supported 为 false 时表示该扩展名尚未支持,此时 Skeleton 为空。
 */
export interface ExtractResult {
    "path": string;
    "skeleton": string;
    "supported": boolean;
}
