// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExtractItem 是骨架提取的单个文件结果。
 * Supported 为 false 时表示该文件扩展名尚未支持,此时 Skeleton 为空。
 * Error 非空时表示该文件在读取 / 解析阶段发生错误(不会中断其他文件)。
 */
export interface ExtractItem {
    "path": string;
    "skeleton": string;
    "supported": boolean;
    "error"?: string;
}

/**
 * ExtractResult 是骨架提取的批量返回结构。
 */
export interface ExtractResult {
    "items": ExtractItem[] | null;
}
