// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SkeletonService 暴露给前端:根据文件路径提取代码骨架。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Extract 读取指定路径的源码文件并返回代码骨架文本。
 * 若语言不受支持,返回 Supported=false,而非错误,便于前端做降级展示。
 */
export function Extract(path: string): $CancellablePromise<$models.ExtractResult | null> {
    return $Call.ByID(362761953, path);
}
