// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SkeletonService 暴露给前端:根据文件或目录路径批量提取代码骨架。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Extract 接收一组路径(文件或目录),对每个可提取的源码文件返回骨架文本。
 * 目录会被递归遍历,自动跳过不受支持的扩展名。
 */
export function Extract(paths: string[] | null): $CancellablePromise<$models.ExtractResult | null> {
    return $Call.ByID(362761953, paths);
}
