// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as context$0 from "../../context/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sql$0 from "../../database/sql/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as clause$0 from "./clause/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as logger$0 from "./logger/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as schema$0 from "./schema/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as reflect$0 from "../../reflect/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as strings$0 from "../../strings/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sync$0 from "../../sync/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

/**
 * ConnPool db conns pool interface
 */
export type ConnPool = any;

/**
 * DB GORM DB definition
 */
export interface DB {
    /**
     * GORM perform single create, update, delete operations in transactions by default to ensure database data integrity
     * You can disable it by setting `SkipDefaultTransaction` to true
     */
    "SkipDefaultTransaction": boolean;
    "DefaultTransactionTimeout": time$0.Duration;
    "DefaultContextTimeout": time$0.Duration;

    /**
     * NamingStrategy tables, columns naming strategy
     */
    "NamingStrategy": schema$0.Namer;

    /**
     * FullSaveAssociations full save associations
     */
    "FullSaveAssociations": boolean;

    /**
     * Logger
     */
    "Logger": logger$0.Interface;

    /**
     * NowFunc the function to be used when creating a new timestamp.
     * It defaults to time.Now().Local(), so return values in the desired
     * location when overriding it for timezone-sensitive applications.
     */
    "NowFunc": any;

    /**
     * DryRun generate sql without execute
     */
    "DryRun": boolean;

    /**
     * PrepareStmt executes the given query in cached statement
     */
    "PrepareStmt": boolean;

    /**
     * PrepareStmt cache support LRU expired,
     * default maxsize=int64 Max value and ttl=1h
     */
    "PrepareStmtMaxSize": number;
    "PrepareStmtTTL": time$0.Duration;

    /**
     * DisableAutomaticPing
     */
    "DisableAutomaticPing": boolean;

    /**
     * DisableForeignKeyConstraintWhenMigrating
     */
    "DisableForeignKeyConstraintWhenMigrating": boolean;

    /**
     * IgnoreRelationshipsWhenMigrating
     */
    "IgnoreRelationshipsWhenMigrating": boolean;

    /**
     * DisableNestedTransaction disable nested transaction
     */
    "DisableNestedTransaction": boolean;

    /**
     * AllowGlobalUpdate allow global update
     */
    "AllowGlobalUpdate": boolean;

    /**
     * QueryFields executes the SQL query with all fields of the table
     */
    "QueryFields": boolean;

    /**
     * CreateBatchSize default create batch size
     */
    "CreateBatchSize": number;

    /**
     * TranslateError enabling error translation
     */
    "TranslateError": boolean;

    /**
     * PropagateUnscoped propagate Unscoped to every other nested statement
     */
    "PropagateUnscoped": boolean;

    /**
     * ClauseBuilders clause builder
     */
    "ClauseBuilders": { [_ in string]?: clause$0.ClauseBuilder } | null;

    /**
     * ConnPool db conn pool
     */
    "ConnPool": ConnPool;

    /**
     * Dialector database dialector
     */
    "Dialector": Dialector;

    /**
     * Plugins registered plugins
     */
    "Plugins": { [_ in string]?: Plugin } | null;
    "Error": any;
    "RowsAffected": number;
    "Statement": Statement | null;
}

/**
 * Dialector GORM database dialector
 */
export type Dialector = any;

/**
 * Plugin GORM plugin interface
 */
export type Plugin = any;

/**
 * Statement statement
 */
export interface Statement {
    /**
     * GORM perform single create, update, delete operations in transactions by default to ensure database data integrity
     * You can disable it by setting `SkipDefaultTransaction` to true
     */
    "SkipDefaultTransaction": boolean;
    "DefaultTransactionTimeout": time$0.Duration;
    "DefaultContextTimeout": time$0.Duration;

    /**
     * NamingStrategy tables, columns naming strategy
     */
    "NamingStrategy": schema$0.Namer;

    /**
     * FullSaveAssociations full save associations
     */
    "FullSaveAssociations": boolean;

    /**
     * Logger
     */
    "Logger": logger$0.Interface;

    /**
     * NowFunc the function to be used when creating a new timestamp.
     * It defaults to time.Now().Local(), so return values in the desired
     * location when overriding it for timezone-sensitive applications.
     */
    "NowFunc": any;

    /**
     * DryRun generate sql without execute
     */
    "DryRun": boolean;

    /**
     * PrepareStmt executes the given query in cached statement
     */
    "PrepareStmt": boolean;

    /**
     * PrepareStmt cache support LRU expired,
     * default maxsize=int64 Max value and ttl=1h
     */
    "PrepareStmtMaxSize": number;
    "PrepareStmtTTL": time$0.Duration;

    /**
     * DisableAutomaticPing
     */
    "DisableAutomaticPing": boolean;

    /**
     * DisableForeignKeyConstraintWhenMigrating
     */
    "DisableForeignKeyConstraintWhenMigrating": boolean;

    /**
     * IgnoreRelationshipsWhenMigrating
     */
    "IgnoreRelationshipsWhenMigrating": boolean;

    /**
     * DisableNestedTransaction disable nested transaction
     */
    "DisableNestedTransaction": boolean;

    /**
     * AllowGlobalUpdate allow global update
     */
    "AllowGlobalUpdate": boolean;

    /**
     * QueryFields executes the SQL query with all fields of the table
     */
    "QueryFields": boolean;

    /**
     * CreateBatchSize default create batch size
     */
    "CreateBatchSize": number;

    /**
     * TranslateError enabling error translation
     */
    "TranslateError": boolean;

    /**
     * PropagateUnscoped propagate Unscoped to every other nested statement
     */
    "PropagateUnscoped": boolean;

    /**
     * ClauseBuilders clause builder
     */
    "ClauseBuilders": { [_ in string]?: clause$0.ClauseBuilder } | null;

    /**
     * Dialector database dialector
     */
    "Dialector": Dialector;

    /**
     * Plugins registered plugins
     */
    "Plugins": { [_ in string]?: Plugin } | null;
    "Error": any;
    "RowsAffected": number;
    "Statement": Statement | null;
    "TableExpr": clause$0.Expr | null;
    "Table": string;
    "Model": any;
    "Unscoped": boolean;
    "Dest": any;
    "ReflectValue": reflect$0.Value;
    "Clauses": { [_ in string]?: clause$0.Clause } | null;
    "BuildClauses": string[] | null;
    "Distinct": boolean;

    /**
     * selected columns
     */
    "Selects": string[] | null;

    /**
     * omit columns
     */
    "Omits": string[] | null;

    /**
     * map columns
     */
    "ColumnMapping": { [_ in string]?: string } | null;
    "Joins": join[] | null;
    "Preloads": { [_ in string]?: any[] | null } | null;
    "Settings": sync$0.Map;
    "ConnPool": ConnPool;
    "Schema": schema$0.Schema | null;
    "Context": context$0.Context;
    "RaiseErrorOnNotFound": boolean;
    "SkipHooks": boolean;
    "SQL": strings$0.Builder;
    "Vars": any[] | null;
    "CurDestIndex": number;
    "Result": result | null;
}

export interface join {
    "Name": string;
    "Alias": string;
    "Conds": any[] | null;
    "On": clause$0.Where | null;
    "Selects": string[] | null;
    "Omits": string[] | null;
    "Expression": clause$0.Expression;
    "JoinType": clause$0.JoinType;
}

export interface result {
    "Result": sql$0.Result;
    "RowsAffected": number;
    "Error": any;
}
