// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DialogService 暴露原生系统对话框给前端使用。
 * 目前仅提供目录选择器,后续如需文件选择/保存对话框可在此扩展。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * PickDirectory 弹出系统目录选择对话框,返回用户选中的绝对路径。
 * 用户取消时返回 Canceled=true,Path="",err=nil。
 */
export function PickDirectory($in: $models.PickDirectoryInput): $CancellablePromise<$models.PickDirectoryResult | null> {
    return $Call.ByID(1059607422, $in);
}

/**
 * SetApp 注入 Wails application 句柄。由 app 包在装配阶段调用。
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(1934203125, app);
}
