// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FilesDroppedPayload 拖放事件转发给前端的负载。
 * Paths 为绝对路径列表;当 native 层提供 DropTargetDetails 时,
 * 一并携带命中的目标元素信息与视口坐标,便于前端精确定位到光标位置插入。
 */
export interface FilesDroppedPayload {
    "paths": string[] | null;
    "x": number;
    "y": number;
    "elementId"?: string;
    "hasCoords": boolean;
}
