// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FilesDroppedPayload 拖放事件转发给前端的负载。
 * Paths 为绝对路径列表。
 * 注:Wails v3 alpha2.117 的 WindowEventContext 未稳定提供拖放坐标,
 * 前端一律落到当前光标位置插入。
 */
export interface FilesDroppedPayload {
    "paths": string[] | null;
}
