// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * A Builder is used to efficiently build a string using [Builder.Write] methods.
 * It minimizes memory copying. The zero value is ready to use.
 * Do not copy a non-zero Builder.
 */
export interface Builder {
}
