// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as FileService from "./fileservice.js";
export {
    FileService
};

export type {
    CreateDirectoryInput,
    DeleteInput,
    FileEntry,
    GenerateTreeInput,
    GenerateTreeResult,
    MovePathInput,
    PasteFromClipboardResult,
    ReadFileResult,
    RenameInput,
    RenameResult,
    WriteFileInput,
    WriteFileResult
} from "./models.js";
