// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CreateDirectoryInput 创建目录入参。BatchID 语义同 WriteFileInput。
 */
export interface CreateDirectoryInput {
    "path": string;
    "batchId"?: number;
}

/**
 * DeleteInput 删除入参。BatchID 语义同 WriteFileInput。
 */
export interface DeleteInput {
    "path": string;
    "batchId"?: number;
}

/**
 * FileEntry 目录列表中的单项元数据。
 */
export interface FileEntry {
    "name": string;
    "path": string;
    "isDir": boolean;
    "size": number;

    /**
     * Unix 秒
     */
    "modTime": number;
}

/**
 * GenerateTreeInput 生成目录树入参。
 */
export interface GenerateTreeInput {
    "paths": string[] | null;

    /**
     * 最大深度限制，防止大型目录导致无限递归
     */
    "maxDepth": number;
}

/**
 * GenerateTreeResult 生成目录树出参。
 */
export interface GenerateTreeResult {
    "treeText": string;
}

/**
 * MovePathInput 文件/目录移动或重命名入参。
 * BatchID 可选:若非零,登记 source 与 destination 的原始状态以支持撤销。
 */
export interface MovePathInput {
    "source": string;
    "destination": string;
    "batchId"?: number;
}

/**
 * PasteFromClipboardResult 描述一次剪贴板粘贴的结果。
 * Written 为写入到目标目录的绝对路径列表;Cut 表示是否按剪切语义执行(源已被删除)。
 */
export interface PasteFromClipboardResult {
    "written": string[] | null;
    "cut": boolean;
}

/**
 * ReadFileResult 读取文件结果。ModTime 为 Unix 秒,用于后续写入时的 data race 检测。
 */
export interface ReadFileResult {
    "path": string;
    "content": string;
    "size": number;
    "modTime": number;
}

/**
 * RenameInput 同级重命名入参。NewName 只能是纯文件名,不能包含分隔符。
 */
export interface RenameInput {
    "path": string;
    "newName": string;
    "batchId"?: number;
}

/**
 * RenameResult 重命名结果。Renamed=false 表示新旧同名,已静默跳过。
 */
export interface RenameResult {
    "path": string;
    "oldPath": string;
    "renamed": boolean;
}

/**
 * WriteFileInput 写文件入参。
 * 若目标目录不存在,自动创建父目录。
 * BatchID 可选:若非零,写盘前登记原始状态以支持后续撤销。
 * ExpectedModTime 可选(Unix 秒):若非零且目标文件已存在,写入前会比对磁盘上的 mtime,
 * 不一致则拒绝写入(data race 保护)。新建文件场景该字段被忽略。
 */
export interface WriteFileInput {
    "path": string;
    "content": string;
    "batchId"?: number;
    "expectedModTime"?: number;
}

/**
 * WriteFileResult 写文件结果,包含 git 风格的 diff 提示。
 * Created=true 表示新建文件(展示"创建文件"),否则展示"编辑文件"。
 */
export interface WriteFileResult {
    "path": string;
    "created": boolean;
    "diff": string;
}
