// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as PromptTemplateService from "./prompttemplateservice.js";
export {
    PromptTemplateService
};

export type {
    CreateInput,
    PromptTemplate,
    UpdateInput
} from "./models.js";
