// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AlwaysOnTopSetter 将"置顶"能力抽象为一个函数,便于解耦具体窗口实现(Wails)。
 * app 层在创建窗口后注入,通常是 window.SetAlwaysOnTop 的闭包。
 */
export type AlwaysOnTopSetter = any;

/**
 * AlwaysOnTopState 返回给前端的置顶状态。
 */
export interface AlwaysOnTopState {
    "enabled": boolean;
}

/**
 * SetAlwaysOnTopInput 前端调用 SetAlwaysOnTop 的入参。
 */
export interface SetAlwaysOnTopInput {
    "enabled": boolean;
}

/**
 * WindowBottomRightMover 将"将窗口移动到屏幕右下角"能力抽象为一个函数。
 * 语义:窗口右边缘贴屏幕工作区右边缘(距离 0),窗口下边缘贴工作区底边缘
 * (即状态栏/任务栏上沿,距离 0)。app 层在创建窗口后注入,内部通过 Wails
 * runtime 获取屏幕工作区尺寸与当前窗口尺寸并调用 SetPosition。
 */
export type WindowBottomRightMover = any;

/**
 * WindowVisibilitySetter 将"显示/隐藏窗口"能力抽象为一个函数。
 * app 层在创建窗口后注入,通常是 window.Show/window.Hide 的闭包封装。
 */
export type WindowVisibilitySetter = any;

/**
 * WindowVisibilityState 返回给前端的窗口可见性状态。
 */
export interface WindowVisibilityState {
    "visible": boolean;
}
