// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService 管理主窗口的用户可持久化设置。
 * 目前实现:置顶状态 (Always On Top)、显示/隐藏(供托盘模式调用)。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as eventbus$0 from "../../pkg/eventbus/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAlwaysOnTop 返回当前置顶状态(内存缓存,与数据库保持同步)。
 */
export function GetAlwaysOnTop(): $CancellablePromise<$models.AlwaysOnTopState | null> {
    return $Call.ByID(3552872408);
}

/**
 * GetVisibility 返回当前窗口可见性状态。
 */
export function GetVisibility(): $CancellablePromise<$models.WindowVisibilityState | null> {
    return $Call.ByID(3119906665);
}

/**
 * Hide 隐藏主窗口。托盘模式下由托盘菜单/关闭拦截等场景调用。
 * 若 setter 未注入则返回错误;若窗口已处于隐藏状态则为幂等操作。
 */
export function Hide(): $CancellablePromise<$models.WindowVisibilityState | null> {
    return $Call.ByID(3883139559);
}

/**
 * LoadPersistedAlwaysOnTop 从数据库读取上次保存的置顶状态。
 * 记录不存在时返回 false,不视为错误。app 层在创建窗口之前调用,
 * 以便用初始状态构造窗口。
 */
export function LoadPersistedAlwaysOnTop(): $CancellablePromise<boolean> {
    return $Call.ByID(1680600991);
}

/**
 * LoadPersistedTrayMode 从数据库读取上次保存的"启动即托盘"偏好。
 * 记录不存在时返回 false。app 层在配置 Wails Options 前调用。
 */
export function LoadPersistedTrayMode(): $CancellablePromise<boolean> {
    return $Call.ByID(1732248519);
}

/**
 * MoveToBottomRight 将主窗口移动到屏幕工作区的右下角,
 * 使窗口右边缘与屏幕右边缘距离为 0、下边缘与状态栏/任务栏上沿距离为 0。
 * 若 mover 未注入则返回错误。
 */
export function MoveToBottomRight(): $CancellablePromise<void> {
    return $Call.ByID(385532294);
}

/**
 * SavePersistedTrayMode 持久化托盘模式偏好,由 TrayService 在
 * EnableTray/DisableTray 成功后回调。
 */
export function SavePersistedTrayMode(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1203437328, enabled);
}

/**
 * SetAlwaysOnTop 设置置顶状态,持久化并应用到窗口。
 * 成功后广播 WindowEventAlwaysOnTopChanged。
 */
export function SetAlwaysOnTop($in: $models.SetAlwaysOnTopInput): $CancellablePromise<$models.AlwaysOnTopState | null> {
    return $Call.ByID(604866508, $in);
}

/**
 * SetBottomRightMover 注入"移动窗口到屏幕右下角"能力。app 层在创建窗口后调用。
 */
export function SetBottomRightMover(mover: $models.WindowBottomRightMover): $CancellablePromise<void> {
    return $Call.ByID(3053917581, mover);
}

/**
 * SetEmitter 注入事件推送能力。
 */
export function SetEmitter(e: eventbus$0.Emitter): $CancellablePromise<void> {
    return $Call.ByID(3550197125, e);
}

/**
 * SetInitialVisibility 由 app 层在创建窗口后调用,同步内存中的初始可见性。
 * 托盘模式启动时应传 false。
 */
export function SetInitialVisibility(visible: boolean): $CancellablePromise<void> {
    return $Call.ByID(3629944559, visible);
}

/**
 * SetSetter 注入窗口置顶设置器。app 层在创建窗口后调用。
 */
export function SetSetter(setter: $models.AlwaysOnTopSetter): $CancellablePromise<void> {
    return $Call.ByID(526148078, setter);
}

/**
 * SetVisibilitySetter 注入窗口显示/隐藏设置器。app 层在创建窗口后调用。
 * setter 语义:传入 true 表示显示窗口(必要时置前),false 表示隐藏窗口。
 */
export function SetVisibilitySetter(setter: $models.WindowVisibilitySetter): $CancellablePromise<void> {
    return $Call.ByID(3015194862, setter);
}

/**
 * Show 显示主窗口。托盘模式下由托盘图标点击/菜单唤出等场景调用。
 * 若 setter 未注入则返回错误;若窗口已处于显示状态则为幂等操作。
 */
export function Show(): $CancellablePromise<$models.WindowVisibilityState | null> {
    return $Call.ByID(2745379946);
}

/**
 * ToggleAlwaysOnTop 翻转当前置顶状态。
 */
export function ToggleAlwaysOnTop(): $CancellablePromise<$models.AlwaysOnTopState | null> {
    return $Call.ByID(2133414970);
}

/**
 * ToggleVisibility 翻转当前显示/隐藏状态,便于托盘图标单击等场景使用。
 */
export function ToggleVisibility(): $CancellablePromise<$models.WindowVisibilityState | null> {
    return $Call.ByID(1049355215);
}
