// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WorkspaceService 负责维护工作区目录树的元数据查询与文件系统监听。
 * 对外暴露给前端的方法在 Wails 端会自动生成 TS 绑定,
 * 因此方法签名应以 JSON 友好类型为主。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as eventbus$0 from "../../pkg/eventbus/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetRoot 返回当前根目录状态。
 */
export function GetRoot(): $CancellablePromise<$models.WorkspaceRootInfo | null> {
    return $Call.ByID(3588886906);
}

/**
 * List 列出指定目录下一层子项。Path 为空表示根目录。
 * 若目录被展开,会自动将其加入监听集合。
 */
export function List($in: $models.ListWorkspaceInput): $CancellablePromise<$models.WorkspaceEntry[] | null> {
    return $Call.ByID(998315902, $in);
}

/**
 * ListAll 递归返回根目录下所有条目(目录 + 文件)的元数据。
 * 前端调用一次即可拿到完整目录树,配合本地搜索命中子目录里的名字。
 * 命中 IgnoreDirs 的目录及其子树整体跳过;单个子目录读取失败会被忽略,不阻断整体。
 * 若 watcher 就绪,过程中会把新遇到的目录加入监听集合。
 */
export function ListAll($in: $models.ListAllWorkspaceInput): $CancellablePromise<$models.WorkspaceEntry[] | null> {
    return $Call.ByID(3135130925, $in);
}

/**
 * Refresh 强制重新读取指定目录一层内容,不区分是否已缓存(前端负责缓存)。
 * 相当于 List 的语义快捷方式,便于前端右键"刷新"直接调用。
 */
export function Refresh($in: $models.ListWorkspaceInput): $CancellablePromise<$models.WorkspaceEntry[] | null> {
    return $Call.ByID(4280791001, $in);
}

/**
 * SetEmitter 由 app 层在构造完 Wails application 后注入,
 * 供 watcher 推送变更事件使用。
 */
export function SetEmitter(e: eventbus$0.Emitter): $CancellablePromise<void> {
    return $Call.ByID(3500696736, e);
}

/**
 * SetRoot 切换根目录,重启监听。
 */
export function SetRoot($in: $models.SetWorkspaceRootInput): $CancellablePromise<$models.WorkspaceRootInfo | null> {
    return $Call.ByID(1180477606, $in);
}

/**
 * Start 启动文件系统监听。若 root 未设置或不存在,返回状态但不报错(降级)。
 */
export function Start(): $CancellablePromise<$models.WorkspaceRootInfo | null> {
    return $Call.ByID(415182874);
}

/**
 * Stop 停止监听。多次调用安全。
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(2020611450);
}
