// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConversationService 提供会话 / 消息 / 消息片段的读写。
 * 
 * AI 消息的解析与执行:AppendMessage 里把 AI 消息内的所有指令拆成 MessageFragment
 * 落库,然后异步交给 FragmentService 逐条自动应用,应用结果通过
 * FragmentUpdatedEvent 推送给前端。前端不再自行解析原文,只按 fragments 渲染。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AppendMessage 向会话末尾追加消息。
 * 
 * 若 in.ConversationID == 0,自动创建新会话。角色识别由后端根据 content 判定,
 * 入参 Role 已被忽略。若判定为 assistant 且含指令,则同事务内把每条指令拆成
 * pending fragment 落库,随后由 FragmentService 异步自动应用并推送状态。
 */
export function AppendMessage($in: $models.AppendMessageInput): $CancellablePromise<$models.AppendMessageResult | null> {
    return $Call.ByID(1507416055, $in);
}

/**
 * ClearMessages 清空消息(不删会话,不影响模板绑定)。
 */
export function ClearMessages(id: number): $CancellablePromise<void> {
    return $Call.ByID(1133732789, id);
}

/**
 * Delete 删除会话及其全部消息、片段与快照批次。
 */
export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByID(3797884675, id);
}

/**
 * DeleteMessage 删除一条消息,连同其 fragments 与关联的快照批次一起删除。
 */
export function DeleteMessage(id: number): $CancellablePromise<void> {
    return $Call.ByID(832293194, id);
}

/**
 * Get 返回会话详情。每条消息的 fragments 已按 order_index 排序并附在 DTO 上。
 */
export function Get(id: number): $CancellablePromise<$models.ConversationDetail | null> {
    return $Call.ByID(2940752644, id);
}

/**
 * List 返回会话摘要列表,置顶项排最前,其后按 updatedAt 倒序。
 */
export function List(): $CancellablePromise<$models.ConversationSummary[] | null> {
    return $Call.ByID(835457888);
}

/**
 * Rename 更新会话标题,并标记为用户覆盖(避免后续自动摘要覆写)。
 */
export function Rename($in: $models.RenameConversationInput): $CancellablePromise<void> {
    return $Call.ByID(976173018, $in);
}

/**
 * SetPinned 切换会话置顶状态。
 */
export function SetPinned($in: $models.SetPinnedInput): $CancellablePromise<void> {
    return $Call.ByID(3656302618, $in);
}

/**
 * SetTemplates 覆盖设置会话绑定的模板集合。
 */
export function SetTemplates($in: $models.SetTemplatesInput): $CancellablePromise<void> {
    return $Call.ByID(982997539, $in);
}

/**
 * UpdateMessage 修改消息正文,并按新内容重建 fragments。
 * 
 * 旧 fragments 会被删除,随后用 BuildFragmentsFromContent 重新解析新内容并落库,
 * 保证前端按 fragments 渲染时看到的是最新文本。返回的 DTO 携带重建后的 fragments。
 * 注意:重建后的指令片段均为 pending,不会自动应用(避免编辑触发意外的文件写入)。
 */
export function UpdateMessage($in: $models.UpdateMessageInput): $CancellablePromise<$models.MessageDTO | null> {
    return $Call.ByID(1944277168, $in);
}
