// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConversationService 提供会话与消息的持久化能力。
 * snapshots 用于会话删除/清空时级联清理批次与快照,通过服务边界调用,
 * 避免本包直接操作 snapshot_batches / file_snapshots 表。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AppendMessage 向会话末尾追加消息。
 * 若 in.ConversationID == 0,自动创建新会话;标题从首条 user 消息摘要生成。
 */
export function AppendMessage($in: $models.AppendMessageInput): $CancellablePromise<$models.AppendMessageResult | null> {
    return $Call.ByID(1507416055, $in);
}

/**
 * ClearMessages 清空消息接口（不删除会话，不影响绑定的模板）
 */
export function ClearMessages(id: number): $CancellablePromise<void> {
    return $Call.ByID(1133732789, id);
}

/**
 * Delete 删除会话及其全部消息与快照批次。
 */
export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByID(3797884675, id);
}

/**
 * DeleteMessage 删除一条消息;若关联了快照批次,一并删除批次与快照数据。
 * 该操作不会撤销文件修改(文件已落地),仅移除记录。
 */
export function DeleteMessage(id: number): $CancellablePromise<void> {
    return $Call.ByID(832293194, id);
}

/**
 * Get 返回会话详情(含消息序列)。
 */
export function Get(id: number): $CancellablePromise<$models.ConversationDetail | null> {
    return $Call.ByID(2940752644, id);
}

/**
 * List 返回会话摘要列表,置顶项排最前,其后按 updatedAt 倒序。
 */
export function List(): $CancellablePromise<$models.ConversationSummary[] | null> {
    return $Call.ByID(835457888);
}

/**
 * Rename 更新会话标题,并标记为用户覆盖(避免后续自动摘要覆写)。
 */
export function Rename($in: $models.RenameConversationInput): $CancellablePromise<void> {
    return $Call.ByID(976173018, $in);
}

/**
 * SetPinned 切换会话置顶状态。
 */
export function SetPinned($in: $models.SetPinnedInput): $CancellablePromise<void> {
    return $Call.ByID(3656302618, $in);
}

/**
 * SetTemplates 覆盖设置会话绑定的模板集合 (前端多选框切换时调用)
 */
export function SetTemplates($in: $models.SetTemplatesInput): $CancellablePromise<void> {
    return $Call.ByID(982997539, $in);
}

/**
 * UpdateMessage 仅修改消息正文,不重放执行。
 */
export function UpdateMessage($in: $models.UpdateMessageInput): $CancellablePromise<$models.MessageDTO | null> {
    return $Call.ByID(1944277168, $in);
}
