// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FragmentService 管理消息片段的生命周期:构建 / 自动应用 / 手动 apply / 编辑 / 忽略。
 * 
 * 该服务与 ConversationService 共用一份数据库,以便在同一事务里插入消息 + fragments。
 * FileService 抽象成 aiproto.FileOps 供文件动作使用;Snapshots 负责 batch 生命周期。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as eventbus$0 from "../../pkg/eventbus/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyFragments 用户主动触发一次应用。FragmentIDs 为空时对整条消息里
 * 所有 pending / match_failed 的 fragment 执行。
 */
export function ApplyFragments($in: $models.ApplyFragmentsInput): $CancellablePromise<$models.ApplyFragmentsResult | null> {
    return $Call.ByID(4054510386, $in);
}

/**
 * AutoApplyMessage 在后台顺序应用一条消息里的所有待应用 fragment。
 * 匹配失败的条目不中断整体,只自身进入 match_failed。
 */
export function AutoApplyMessage(convID: number, messageID: number): $CancellablePromise<void> {
    return $Call.ByID(3779088371, convID, messageID);
}

/**
 * SetEmitter 注入事件推送能力。
 */
export function SetEmitter(e: eventbus$0.Emitter): $CancellablePromise<void> {
    return $Call.ByID(1868923985, e);
}

/**
 * SetFragmentStatus 只支持 pending ↔ ignored 切换。其他状态不受此接口影响。
 */
export function SetFragmentStatus($in: $models.SetFragmentStatusInput): $CancellablePromise<$models.MessageFragmentDTO | null> {
    return $Call.ByID(9539987, $in);
}

/**
 * UpdateFragment 编辑失败片段的内容,并把状态重置为 pending 供再次应用。
 */
export function UpdateFragment($in: $models.UpdateFragmentInput): $CancellablePromise<$models.MessageFragmentDTO | null> {
    return $Call.ByID(1046163834, $in);
}
