// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as ConversationService from "./conversationservice.js";
export {
    ConversationService
};

export type {
    AppendMessageInput,
    AppendMessageResult,
    ConversationDetail,
    ConversationSummary,
    MessageDTO,
    RenameConversationInput,
    SetPinnedInput,
    SetTemplatesInput,
    UpdateMessageInput
} from "./models.js";
