// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppendMessageInput 追加消息入参。
 * 若 ConversationID 为 0,后端会自动创建新会话并返回新 id。
 * Role 已被弃用:后端根据 content 中是否含指令标签自行判定;字段保留仅为兼容旧调用。
 */
export interface AppendMessageInput {
    "conversationId": number;

    /**
     * deprecated
     */
    "role"?: string;
    "content": string;
    "batchId": number;
}

/**
 * AppendMessageResult 追加消息结果。
 */
export interface AppendMessageResult {
    "conversationId": number;
    "message": MessageDTO;

    /**
     * 是否为本次调用新建的会话
     */
    "createdNew": boolean;
}

/**
 * ApplyFragmentsInput 批量应用入参。若 FragmentIDs 为空,则对该消息所有
 * 可应用(pending / match_failed)的片段依次执行。
 */
export interface ApplyFragmentsInput {
    "messageId": number;
    "fragmentIds"?: number[] | null;
}

/**
 * ApplyFragmentsResult 返回本次触发后所有相关 fragment 的最新态,以便前端一次性合并。
 */
export interface ApplyFragmentsResult {
    "fragments": MessageFragmentDTO[] | null;
}

/**
 * ConversationDetail 会话详情:包含元数据 + 消息序列。
 */
export interface ConversationDetail {
    "conversation": ConversationSummary;
    "messages": MessageDTO[] | null;
}

/**
 * ConversationSummary 会话列表项。
 */
export interface ConversationSummary {
    "id": number;
    "title": string;
    "titleOverridden": boolean;
    "pinned": boolean;
    "messageCount": number;

    /**
     * 该会话关联的模板集合
     */
    "templateIds": number[] | null;

    /**
     * RFC3339
     */
    "createdAt": string;
    "updatedAt": string;
}

/**
 * MessageDTO 单条消息的传输结构。
 * Fragments 只在 AI 消息里非空:每条 AI 消息可拆出零至多个修改片段,
 * 前端按此渲染卡片、驱动应用/编辑/忽略等操作。
 */
export interface MessageDTO {
    "id": number;
    "conversationId": number;
    "role": string;
    "content": string;
    "batchId": number;
    "createdAt": string;
    "updatedAt": string;
    "fragments": MessageFragmentDTO[] | null;
}

/**
 * MessageFragmentDTO 单个修改片段的传输结构。
 */
export interface MessageFragmentDTO {
    "id": number;
    "messageId": number;
    "orderIndex": number;
    "kind": string;
    "path": string;
    "destination": string;
    "rawStart": number;
    "rawEnd": number;
    "blockIndex": number;
    "before": string;
    "after": string;
    "status": string;
    "matchReason": string;
    "appliedAt"?: string;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * RenameConversationInput 重命名会话入参。
 */
export interface RenameConversationInput {
    "conversationId": number;
    "title": string;
}

/**
 * SetFragmentStatusInput 设置片段状态,当前仅支持 ignored / pending 两态切换。
 */
export interface SetFragmentStatusInput {
    "fragmentId": number;

    /**
     * "ignored" | "pending"
     */
    "status": string;
}

/**
 * SetPinnedInput 置顶/取消置顶入参。
 */
export interface SetPinnedInput {
    "conversationId": number;
    "pinned": boolean;
}

/**
 * SetTemplatesInput 保存会话启用的模板集合。
 */
export interface SetTemplatesInput {
    "conversationId": number;
    "templateIds": number[] | null;
}

/**
 * UpdateFragmentInput 修改片段的编辑内容/目标位置入参。
 * 未设置的字段(nil 或空)不被覆盖。为了保持简单,这里区分"未提供"用零值 + 字段:
 * 使用指针可以避免歧义。
 */
export interface UpdateFragmentInput {
    "fragmentId": number;
    "path"?: string | null;
    "destination"?: string | null;
    "before"?: string | null;
    "after"?: string | null;
}

/**
 * UpdateMessageInput 修改消息正文入参。
 */
export interface UpdateMessageInput {
    "messageId": number;
    "content": string;
}
