// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppendMessageInput 追加消息入参。
 * 若 ConversationID 为 0,后端会自动创建新会话并返回新 id。
 */
export interface AppendMessageInput {
    "conversationId": number;

    /**
     * "user" | "assistant"
     */
    "role": string;
    "content": string;

    /**
     * 可选:关联的快照批次
     */
    "batchId": number;
}

/**
 * AppendMessageResult 追加消息结果。
 */
export interface AppendMessageResult {
    "conversationId": number;
    "message": MessageDTO;

    /**
     * 是否为本次调用新建的会话
     */
    "createdNew": boolean;
}

/**
 * ConversationDetail 会话详情:包含元数据 + 消息序列。
 */
export interface ConversationDetail {
    "conversation": ConversationSummary;
    "messages": MessageDTO[] | null;
}

/**
 * ConversationSummary 会话列表项。
 */
export interface ConversationSummary {
    "id": number;
    "title": string;
    "titleOverridden": boolean;
    "pinned": boolean;
    "messageCount": number;

    /**
     * 该会话关联的模板集合
     */
    "templateIds": number[] | null;

    /**
     * RFC3339
     */
    "createdAt": string;
    "updatedAt": string;
}

/**
 * MessageDTO 单条消息的传输结构。
 */
export interface MessageDTO {
    "id": number;
    "conversationId": number;
    "role": string;
    "content": string;
    "batchId": number;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * RenameConversationInput 重命名会话入参。
 */
export interface RenameConversationInput {
    "conversationId": number;
    "title": string;
}

/**
 * SetPinnedInput 置顶/取消置顶入参。
 */
export interface SetPinnedInput {
    "conversationId": number;
    "pinned": boolean;
}

/**
 * SetTemplatesInput 保存会话启用的模板集合。
 */
export interface SetTemplatesInput {
    "conversationId": number;
    "templateIds": number[] | null;
}

/**
 * UpdateMessageInput 修改消息正文入参。
 */
export interface UpdateMessageInput {
    "messageId": number;
    "content": string;
}
