// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BatchStatus 批次状态,用于前端渲染撤销入口。
 */
export interface BatchStatus {
    "batchId": number;
    "messageId": number;
    "fileCount": number;
    "createdAt": string;

    /**
     * 非空表示已撤销
     */
    "undoneAt"?: string;

    /**
     * StaleWarning=true 表示批次内某些文件在此后又被其它批次修改过,
     * 撤销时会覆盖那些较新的修改。
     */
    "staleWarning": boolean;
}

/**
 * BeginBatchInput 开启快照批次入参。
 * MessageID 为触发该批次的 AI 消息 id;可为 0(先执行、后落库),之后再 Bind。
 */
export interface BeginBatchInput {
    "conversationId": number;
    "messageId": number;
}

/**
 * BeginBatchResult 开启批次结果。
 */
export interface BeginBatchResult {
    "batchId": number;
}

/**
 * BindBatchInput 将已开启的批次绑定到最终落库的 AI 消息 id。
 */
export interface BindBatchInput {
    "batchId": number;
    "messageId": number;
}

/**
 * UndoBatchResult 撤销结果概览。
 */
export interface UndoBatchResult {
    "batchId": number;
    "restoredPaths": string[] | null;
    "warnings": string[] | null;
}
