// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SnapshotService 负责文件修改批次的快照登记与撤销。
 * 与 FileService 之间的耦合通过导出的 RecordIfNeeded 方法实现:FileService 在实际写盘前
 * 调用 SnapshotService.RecordIfNeeded 将原始内容登记为快照。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gorm$0 from "../../../../gorm.io/gorm/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BeginBatch 开启一个空批次,返回 batchID。
 * MessageID 允许为 0(尚未落库),稍后调用 Bind 绑定。
 */
export function BeginBatch($in: $models.BeginBatchInput): $CancellablePromise<$models.BeginBatchResult | null> {
    return $Call.ByID(1555704237, $in);
}

/**
 * Bind 将批次关联到最终落库的 AI 消息 id。
 */
export function Bind($in: $models.BindBatchInput): $CancellablePromise<void> {
    return $Call.ByID(3344443653, $in);
}

/**
 * DeleteBatchTx 在给定事务中删除单个批次及其快照文件。
 * 由 ConversationService.DeleteMessage 在删除关联消息时调用。
 */
export function DeleteBatchTx(tx: gorm$0.DB | null, batchID: number): $CancellablePromise<void> {
    return $Call.ByID(3195742755, tx, batchID);
}

/**
 * DeleteByConversationTx 在给定事务中删除某会话名下的所有批次与快照文件。
 * 由 ConversationService 在删除/清空会话时调用,保持 snapshot 域自治:
 * 表结构与领域规则(比如仅删数据不做撤销回滚)都由本包决定,
 * conversation 不再直接触碰 snapshot_batches / file_snapshots 表。
 */
export function DeleteByConversationTx(tx: gorm$0.DB | null, convID: number): $CancellablePromise<void> {
    return $Call.ByID(3884906563, tx, convID);
}

/**
 * RecordIfNeeded 若 batchID != 0,在实际写盘/删除/移动前登记原始内容。
 * 幂等语义交给上层:同一路径可多次登记,以时间序保留;还原时用最早那次。
 * 该方法供 file 域 Service 跨包调用。
 */
export function RecordIfNeeded(batchID: number, absPath: string): $CancellablePromise<void> {
    return $Call.ByID(3626655085, batchID, absPath);
}

/**
 * Status 查询一个批次的状态摘要;供前端渲染撤销入口。
 */
export function Status(batchID: number): $CancellablePromise<$models.BatchStatus | null> {
    return $Call.ByID(2455691592, batchID);
}

/**
 * Undo 撤销一个批次:将其中登记的所有路径回滚到批次开启前的状态。
 * 已撤销的批次再次调用将报错。
 */
export function Undo(batchID: number): $CancellablePromise<$models.UndoBatchResult | null> {
    return $Call.ByID(3120740404, batchID);
}
