// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Clause
 */
export interface Clause {
    /**
     * WHERE
     */
    "Name": string;
    "BeforeExpression": Expression;
    "AfterNameExpression": Expression;
    "AfterExpression": Expression;
    "Expression": Expression;
    "Builder": ClauseBuilder;
}

/**
 * ClauseBuilder clause builder, allows to customize how to build clause
 */
export type ClauseBuilder = any;

/**
 * Expr raw expression
 */
export interface Expr {
    "SQL": string;
    "Vars": any[] | null;
    "WithoutParentheses": boolean;
}

/**
 * Expression expression interface
 */
export type Expression = any;

/**
 * Interface clause interface
 */
export type Interface = any;

export enum JoinType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CrossJoin = "CROSS",
    InnerJoin = "INNER",
    LeftJoin = "LEFT",
    RightJoin = "RIGHT",
};

/**
 * Where where clause
 */
export interface Where {
    "Exprs": Expression[] | null;
}
