// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * A StructField describes a single field in a struct.
 */
export interface StructField {
    /**
     * Name is the field name.
     */
    "Name": string;

    /**
     * PkgPath is the package path that qualifies a lower case (unexported)
     * field name. It is empty for upper case (exported) field names.
     * See https://golang.org/ref/spec#Uniqueness_of_identifiers
     */
    "PkgPath": string;

    /**
     * field type
     */
    "Type": Type;

    /**
     * field tag string
     */
    "Tag": StructTag;

    /**
     * offset within struct, in bytes
     */
    "Offset": number;

    /**
     * index sequence for Type.FieldByIndex
     */
    "Index": number[] | null;

    /**
     * is an embedded field
     */
    "Anonymous": boolean;
}

/**
 * A StructTag is the tag string in a struct field.
 * 
 * By convention, tag strings are a concatenation of
 * optionally space-separated key:"value" pairs.
 * Each key is a non-empty string consisting of non-control
 * characters other than space (U+0020 ' '), quote (U+0022 '"'),
 * and colon (U+003A ':').  Each value is quoted using U+0022 '"'
 * characters and Go string literal syntax.
 */
export type StructTag = string;

/**
 * Type is the representation of a Go type.
 * 
 * Not all methods apply to all kinds of types. Restrictions,
 * if any, are noted in the documentation for each method.
 * Use the Kind method to find out the kind of type before
 * calling kind-specific methods. Calling a method
 * inappropriate to the kind of type causes a run-time panic.
 * 
 * Type values are comparable, such as with the == operator,
 * so they can be used as map keys.
 * Two Type values are equal if they represent identical types.
 */
export type Type = any;

/**
 * Value is the reflection interface to a Go value.
 * 
 * Not all methods apply to all kinds of values. Restrictions,
 * if any, are noted in the documentation for each method.
 * Use the Kind method to find out the kind of value before
 * calling kind-specific methods. Calling a method
 * inappropriate to the kind of type causes a run time panic.
 * 
 * The zero Value represents no value.
 * Its [Value.IsValid] method returns false, its Kind method returns [Invalid],
 * its String method returns "<invalid Value>", and all other methods panic.
 * Most functions and methods never return an invalid value.
 * If one does, its documentation states the conditions explicitly.
 * 
 * A Value can be used concurrently by multiple goroutines provided that
 * the underlying Go value can be used concurrently for the equivalent
 * direct operations.
 * 
 * To compare two Values, compare the results of the Interface method.
 * Using == on two Values does not compare the underlying values
 * they represent.
 */
export interface Value {
}
