// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ClearRecentInput 前端调用 Clear 的入参。
 * 当前模型不含 pinned 字段,该参数为将来预留;若为 true 目前不清空(无 pinned 概念时等同 false)。
 */
export interface ClearRecentInput {
}

/**
 * ListRecentInput 前端调用 List 的入参。
 */
export interface ListRecentInput {
}

/**
 * RecentItem 记录用户最近打开的目录或文件。
 */
export interface RecentItem {
    "id": number;
    "path": string;

    /**
     * "dir" | "file"
     */
    "kind": string;
    "openedAt": string;
}

/**
 * RemoveRecentInput 前端调用 Remove 的入参。
 */
export interface RemoveRecentInput {
    "id": number;
}
