// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RecentService 负责记录、查询、清理"最近打开"条目,
 * 并在数据变更后通过 Emitter 通知前端刷新。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as eventbus$0 from "../../pkg/eventbus/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Clear 清空最近记录。
 */
export function Clear($in: $models.ClearRecentInput): $CancellablePromise<void> {
    return $Call.ByID(4242801353, $in);
}

/**
 * List 返回按 OpenedAt 降序排列的最近条目。
 */
export function List($in: $models.ListRecentInput): $CancellablePromise<$models.RecentItem[] | null> {
    return $Call.ByID(2957260156, $in);
}

/**
 * Record 规范化路径后 upsert 一条最近打开记录。
 * - 存在则更新 OpenedAt=now;不存在则新建;
 * - 超过 RecentMaxItems 时删除最老记录;
 * - 成功后推送 RecentEventChanged 事件。
 */
export function Record(path: string): $CancellablePromise<$models.RecentItem | null> {
    return $Call.ByID(353518401, path);
}

/**
 * Remove 根据 ID 删除一条记录。
 */
export function Remove($in: $models.RemoveRecentInput): $CancellablePromise<void> {
    return $Call.ByID(293238916, $in);
}

/**
 * SetEmitter 由 app 层注入事件推送能力。
 */
export function SetEmitter(e: eventbus$0.Emitter): $CancellablePromise<void> {
    return $Call.ByID(3390214410, e);
}
