// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConversationService 提供会话与消息的持久化能力。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AppendMessage 向会话末尾追加消息。
 * 若 in.ConversationID == 0,自动创建新会话;标题从首条 user 消息摘要生成。
 */
export function AppendMessage($in: $models.AppendMessageInput): $CancellablePromise<$models.AppendMessageResult | null> {
    return $Call.ByID(2324163641, $in);
}

/**
 * Delete 删除会话及其全部消息与快照批次。
 */
export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByID(1352345729, id);
}

/**
 * DeleteMessage 删除一条消息;若关联了快照批次,一并删除批次与快照数据。
 * 该操作不会撤销文件修改(文件已落地),仅移除记录。
 */
export function DeleteMessage(id: number): $CancellablePromise<void> {
    return $Call.ByID(1010160920, id);
}

/**
 * Get 返回会话详情(含消息序列)。
 */
export function Get(id: number): $CancellablePromise<$models.ConversationDetail | null> {
    return $Call.ByID(473131746, id);
}

/**
 * List 返回会话摘要列表,按 updatedAt 倒序。
 */
export function List(): $CancellablePromise<$models.ConversationSummary[] | null> {
    return $Call.ByID(4052571346);
}

/**
 * Rename 更新会话标题,并标记为用户覆盖(避免后续自动摘要覆写)。
 */
export function Rename($in: $models.RenameConversationInput): $CancellablePromise<void> {
    return $Call.ByID(502248480, $in);
}

/**
 * UpdateMessage 仅修改消息正文,不重放执行。
 */
export function UpdateMessage($in: $models.UpdateMessageInput): $CancellablePromise<$models.MessageDTO | null> {
    return $Call.ByID(1179119406, $in);
}
