// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService 提供文件与目录的基础操作,暴露给前端调用。
 * 所有路径要求绝对路径,内部会做 Clean 归一化。
 * 若入参中提供 batchID,写/删/移动前会调用 SnapshotService 登记原始状态,
 * 便于后续按批次撤销。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CopyPathsToWorkspace 将 srcPaths 中的每个文件/目录复制到 workspaceDir。
 * Cut=true 时,单项复制成功后立即删除对应源(剪切语义)。
 * 目标同名自动重命名为 "name (1).ext"、"name (2).ext" 等。
 * 任一源失败即中止,返回此前已成功写入的目标绝对路径与错误。
 */
export function CopyPathsToWorkspace(srcPaths: string[] | null, workspaceDir: string, cut: boolean): $CancellablePromise<string[] | null> {
    return $Call.ByID(1348664340, srcPaths, workspaceDir, cut);
}

/**
 * CreateDirectory 创建目录,包含所有必要的父目录。
 * 保留原有签名以兼容旧调用;带批次撤销能力请使用 CreateDirectoryWithBatch。
 */
export function CreateDirectory(path: string): $CancellablePromise<void> {
    return $Call.ByID(1541732614, path);
}

/**
 * CreateDirectoryWithBatch 与 CreateDirectory 语义一致,额外支持关联快照批次。
 */
export function CreateDirectoryWithBatch($in: $models.CreateDirectoryInput): $CancellablePromise<void> {
    return $Call.ByID(2497541966, $in);
}

/**
 * Delete 删除文件或空目录;若是目录会递归删除。
 * 保留原有签名以兼容旧调用;带批次撤销能力请使用 DeleteWithBatch。
 */
export function Delete(path: string): $CancellablePromise<void> {
    return $Call.ByID(2936146836, path);
}

/**
 * DeleteWithBatch 与 Delete 语义一致,额外支持关联快照批次。
 */
export function DeleteWithBatch($in: $models.DeleteInput): $CancellablePromise<void> {
    return $Call.ByID(714474868, $in);
}

/**
 * GenerateTree 为选定的文件或目录生成类似 tree 命令的结构文本。
 */
export function GenerateTree($in: $models.GenerateTreeInput): $CancellablePromise<$models.GenerateTreeResult | null> {
    return $Call.ByID(1306658312, $in);
}

/**
 * List 列出目录内容(非递归),目录在前、名称升序。
 */
export function List(path: string): $CancellablePromise<$models.FileEntry[] | null> {
    return $Call.ByID(2928397551, path);
}

/**
 * Move 移动或重命名文件/目录。目标已存在则报错。
 * 若 in.BatchID != 0,会同时登记 source(存在) 与 destination(不存在) 的原始状态。
 */
export function Move($in: $models.MovePathInput): $CancellablePromise<void> {
    return $Call.ByID(2946677758, $in);
}

/**
 * OpenInExplorer 在系统文件管理器中打开指定路径，并尽可能选中该文件/目录。
 */
export function OpenInExplorer(path: string): $CancellablePromise<void> {
    return $Call.ByID(3078032335, path);
}

/**
 * PasteFromClipboard 从系统剪贴板读取文件路径,并粘贴到 workspaceDir。
 * - 若剪贴板不含文件路径,返回空 Written 与 nil 错误(调用方可据此提示或降级)。
 * - 剪切语义由剪贴板自身携带(Windows 下的 Preferred DropEffect);
 *   在支持的平台上,粘贴成功后会删除源文件。
 * - 目标同名自动重命名,规则与 CopyPathsToWorkspace 保持一致。
 */
export function PasteFromClipboard(workspaceDir: string): $CancellablePromise<$models.PasteFromClipboardResult | null> {
    return $Call.ByID(1430703448, workspaceDir);
}

/**
 * Read 读取文件内容。
 */
export function Read(path: string): $CancellablePromise<$models.ReadFileResult | null> {
    return $Call.ByID(1275366123, path);
}

/**
 * Rename 在同一父目录内重命名文件/目录。
 * 若 newName 与原名相同,静默返回;若目标已存在,报错;若目标只读,会先清除只读属性。
 * 若 in.BatchID != 0,登记原路径与新路径的原始状态。
 */
export function Rename($in: $models.RenameInput): $CancellablePromise<$models.RenameResult | null> {
    return $Call.ByID(1470862269, $in);
}

/**
 * Write 写入文件内容,自动创建父目录。
 * 返回是否为新建以及 unified diff(与旧内容对比)。
 * 若 in.BatchID != 0,写盘前会登记原始状态用于撤销。
 */
export function Write($in: $models.WriteFileInput): $CancellablePromise<$models.WriteFileResult | null> {
    return $Call.ByID(2571361002, $in);
}

/**
 * WriteBytesToWorkspace 将字节流写入 workspaceDir 下的 fileName。
 * fileName 必须为纯文件名,不允许包含路径分隔符或 "..";同名自动重命名。
 */
export function WriteBytesToWorkspace(fileName: string, data: string | null, workspaceDir: string): $CancellablePromise<string> {
    return $Call.ByID(3890009509, fileName, data, workspaceDir);
}
