// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GreetService 提供给前端的示例服务,后续可按需替换或删除。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Greet 返回问候语。
 */
export function Greet(name: string): $CancellablePromise<string> {
    return $Call.ByID(259013577, name);
}
