// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppendMessageInput 追加消息入参。
 * 若 ConversationID 为 0,后端会自动创建新会话并返回新 id。
 */
export interface AppendMessageInput {
    "conversationId": number;

    /**
     * "user" | "assistant"
     */
    "role": string;
    "content": string;

    /**
     * 可选:关联的快照批次
     */
    "batchId": number;
}

/**
 * AppendMessageResult 追加消息结果。
 */
export interface AppendMessageResult {
    "conversationId": number;
    "message": MessageDTO;

    /**
     * 是否为本次调用新建的会话
     */
    "createdNew": boolean;
}

/**
 * BatchStatus 批次状态,用于前端渲染撤销入口。
 */
export interface BatchStatus {
    "batchId": number;
    "messageId": number;
    "fileCount": number;
    "createdAt": string;

    /**
     * 非空表示已撤销
     */
    "undoneAt"?: string;

    /**
     * StaleWarning=true 表示批次内某些文件在此后又被其它批次修改过,
     * 撤销时会覆盖那些较新的修改。
     */
    "staleWarning": boolean;
}

/**
 * BeginBatchInput 开启快照批次入参。
 * MessageID 为触发该批次的 AI 消息 id;可为 0(先执行、后落库),之后再 Bind。
 */
export interface BeginBatchInput {
    "conversationId": number;
    "messageId": number;
}

/**
 * BeginBatchResult 开启批次结果。
 */
export interface BeginBatchResult {
    "batchId": number;
}

/**
 * BindBatchInput 将已开启的批次绑定到最终落库的 AI 消息 id。
 */
export interface BindBatchInput {
    "batchId": number;
    "messageId": number;
}

/**
 * ConversationDetail 会话详情:包含元数据 + 消息序列。
 */
export interface ConversationDetail {
    "conversation": ConversationSummary;
    "messages": MessageDTO[] | null;
}

/**
 * ConversationSummary 会话列表项。
 */
export interface ConversationSummary {
    "id": number;
    "title": string;
    "titleOverridden": boolean;
    "messageCount": number;

    /**
     * 该会话关联的模板集合
     */
    "templateIds": number[] | null;

    /**
     * RFC3339
     */
    "createdAt": string;
    "updatedAt": string;
}

/**
 * CreateDirectoryInput 创建目录入参。BatchID 语义同 WriteFileInput。
 */
export interface CreateDirectoryInput {
    "path": string;
    "batchId"?: number;
}

/**
 * CreateInput 新建入参。
 */
export interface CreateInput {
    "title": string;
    "content": string;
}

/**
 * DeleteInput 删除入参。BatchID 语义同 WriteFileInput。
 */
export interface DeleteInput {
    "path": string;
    "batchId"?: number;
}

/**
 * Emitter 抽象事件推送能力,便于解耦 Wails application 依赖与测试。
 */
export type Emitter = any;

/**
 * FileEntry 目录列表中的单项元数据。
 */
export interface FileEntry {
    "name": string;
    "path": string;
    "isDir": boolean;
    "size": number;

    /**
     * Unix 秒
     */
    "modTime": number;
}

/**
 * ListWorkspaceInput 列出目录一层内容的入参。
 * Path 为空时使用当前根目录;非空时必须位于根目录之内。
 */
export interface ListWorkspaceInput {
    "path"?: string;
    "includeHidden"?: boolean;
}

/**
 * MessageDTO 单条消息的传输结构。
 */
export interface MessageDTO {
    "id": number;
    "conversationId": number;
    "role": string;
    "content": string;
    "batchId": number;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * MovePathInput 文件/目录移动或重命名入参。
 * BatchID 可选:若非零,登记 source 与 destination 的原始状态以支持撤销。
 */
export interface MovePathInput {
    "source": string;
    "destination": string;
    "batchId"?: number;
}

/**
 * PromptTemplate 提示词模板持久化模型。
 */
export interface PromptTemplate {
    "id": number;
    "title": string;
    "content": string;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * ReadFileResult 读取文件结果。
 */
export interface ReadFileResult {
    "path": string;
    "content": string;
    "size": number;
}

/**
 * RenameConversationInput 重命名会话入参。
 */
export interface RenameConversationInput {
    "conversationId": number;
    "title": string;
}

/**
 * SetTemplatesInput 保存会话启用的模板集合。
 */
export interface SetTemplatesInput {
    "conversationId": number;
    "templateIds": number[] | null;
}

/**
 * SetWorkspaceRootInput 设置根目录入参。
 */
export interface SetWorkspaceRootInput {
    "root": string;
}

/**
 * UndoBatchResult 撤销结果概览。
 */
export interface UndoBatchResult {
    "batchId": number;
    "restoredPaths": string[] | null;
    "warnings": string[] | null;
}

/**
 * UpdateInput 修改入参。
 */
export interface UpdateInput {
    "id": number;
    "title": string;
    "content": string;
}

/**
 * UpdateMessageInput 修改消息正文入参。
 */
export interface UpdateMessageInput {
    "messageId": number;
    "content": string;
}

/**
 * WorkspaceEntry 目录树中的单项元数据。
 * 字段设计与 FileEntry 保持一致的命名风格,并增加 IsHidden / IsSymlink
 * 供前端做视觉区分。
 */
export interface WorkspaceEntry {
    "name": string;
    "path": string;
    "parent": string;
    "isDir": boolean;
    "isHidden": boolean;
    "isSymlink": boolean;
    "size": number;

    /**
     * Unix 秒
     */
    "modTime": number;
}

/**
 * WorkspaceRootInfo 工作区根目录状态。
 */
export interface WorkspaceRootInfo {
    "root": string;
    "exists": boolean;
    "watching": boolean;

    /**
     * fsnotify 不可用,已降级为轮询
     */
    "degraded": boolean;
    "reason"?: string;
}

/**
 * WriteFileInput 写文件入参。
 * 若目标目录不存在,自动创建父目录。
 * BatchID 可选:若非零,写盘前登记原始状态以支持后续撤销。
 */
export interface WriteFileInput {
    "path": string;
    "content": string;
    "batchId"?: number;
}

/**
 * WriteFileResult 写文件结果,包含 git 风格的 diff 提示。
 * Created=true 表示新建文件(展示"创建文件"),否则展示"编辑文件"。
 */
export interface WriteFileResult {
    "path": string;
    "created": boolean;
    "diff": string;
}
