// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AlwaysOnTopSetter 将"置顶"能力抽象为一个函数,便于解耦具体窗口实现(Wails)。
 * app 层在创建窗口后注入,通常是 window.SetAlwaysOnTop 的闭包。
 */
export type AlwaysOnTopSetter = any;

/**
 * AlwaysOnTopState 返回给前端的置顶状态。
 */
export interface AlwaysOnTopState {
    "enabled": boolean;
}

/**
 * AppendMessageInput 追加消息入参。
 * 若 ConversationID 为 0,后端会自动创建新会话并返回新 id。
 */
export interface AppendMessageInput {
    "conversationId": number;

    /**
     * "user" | "assistant"
     */
    "role": string;
    "content": string;

    /**
     * 可选:关联的快照批次
     */
    "batchId": number;
}

/**
 * AppendMessageResult 追加消息结果。
 */
export interface AppendMessageResult {
    "conversationId": number;
    "message": MessageDTO;

    /**
     * 是否为本次调用新建的会话
     */
    "createdNew": boolean;
}

/**
 * BatchStatus 批次状态,用于前端渲染撤销入口。
 */
export interface BatchStatus {
    "batchId": number;
    "messageId": number;
    "fileCount": number;
    "createdAt": string;

    /**
     * 非空表示已撤销
     */
    "undoneAt"?: string;

    /**
     * StaleWarning=true 表示批次内某些文件在此后又被其它批次修改过,
     * 撤销时会覆盖那些较新的修改。
     */
    "staleWarning": boolean;
}

/**
 * BeginBatchInput 开启快照批次入参。
 * MessageID 为触发该批次的 AI 消息 id;可为 0(先执行、后落库),之后再 Bind。
 */
export interface BeginBatchInput {
    "conversationId": number;
    "messageId": number;
}

/**
 * BeginBatchResult 开启批次结果。
 */
export interface BeginBatchResult {
    "batchId": number;
}

/**
 * BindBatchInput 将已开启的批次绑定到最终落库的 AI 消息 id。
 */
export interface BindBatchInput {
    "batchId": number;
    "messageId": number;
}

/**
 * ClearRecentInput 前端调用 Clear 的入参。
 * 当前模型不含 pinned 字段,该参数为将来预留;若为 true 目前不清空(无 pinned 概念时等同 false)。
 */
export interface ClearRecentInput {
}

/**
 * ClipboardPaths 表示从系统剪贴板读取到的文件路径集合及其操作语义。
 * Cut=true 表示系统剪贴板标记为"剪切"(Windows 下 Preferred DropEffect=2),
 * 粘贴方应在复制成功后删除源文件。
 */
export interface ClipboardPaths {
    "paths": string[] | null;
    "cut": boolean;
}

/**
 * ConversationDetail 会话详情:包含元数据 + 消息序列。
 */
export interface ConversationDetail {
    "conversation": ConversationSummary;
    "messages": MessageDTO[] | null;
}

/**
 * ConversationSummary 会话列表项。
 */
export interface ConversationSummary {
    "id": number;
    "title": string;
    "titleOverridden": boolean;
    "pinned": boolean;
    "messageCount": number;

    /**
     * 该会话关联的模板集合
     */
    "templateIds": number[] | null;

    /**
     * RFC3339
     */
    "createdAt": string;
    "updatedAt": string;
}

/**
 * CreateDirectoryInput 创建目录入参。BatchID 语义同 WriteFileInput。
 */
export interface CreateDirectoryInput {
    "path": string;
    "batchId"?: number;
}

/**
 * CreateInput 新建入参。
 */
export interface CreateInput {
    "title": string;
    "content": string;
}

/**
 * DeleteInput 删除入参。BatchID 语义同 WriteFileInput。
 */
export interface DeleteInput {
    "path": string;
    "batchId"?: number;
}

/**
 * Emitter 抽象事件推送能力,便于解耦 Wails application 依赖与测试。
 */
export type Emitter = any;

/**
 * FileEntry 目录列表中的单项元数据。
 */
export interface FileEntry {
    "name": string;
    "path": string;
    "isDir": boolean;
    "size": number;

    /**
     * Unix 秒
     */
    "modTime": number;
}

/**
 * GenerateTreeInput 生成目录树入参。
 */
export interface GenerateTreeInput {
    "paths": string[] | null;

    /**
     * 最大深度限制，防止大型目录导致无限递归
     */
    "maxDepth": number;
}

/**
 * GenerateTreeResult 生成目录树出参。
 */
export interface GenerateTreeResult {
    "treeText": string;
}

/**
 * ListRecentInput 前端调用 List 的入参。
 */
export interface ListRecentInput {
}

/**
 * ListWorkspaceInput 列出目录一层内容的入参。
 * Path 为空时使用当前根目录;非空时必须位于根目录之内。
 */
export interface ListWorkspaceInput {
    "path"?: string;
    "includeHidden"?: boolean;
}

/**
 * MessageDTO 单条消息的传输结构。
 */
export interface MessageDTO {
    "id": number;
    "conversationId": number;
    "role": string;
    "content": string;
    "batchId": number;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * MovePathInput 文件/目录移动或重命名入参。
 * BatchID 可选:若非零,登记 source 与 destination 的原始状态以支持撤销。
 */
export interface MovePathInput {
    "source": string;
    "destination": string;
    "batchId"?: number;
}

/**
 * PasteFromClipboardResult 描述一次剪贴板粘贴的结果。
 * Written 为写入到目标目录的绝对路径列表;Cut 表示是否按剪切语义执行(源已被删除)。
 */
export interface PasteFromClipboardResult {
    "written": string[] | null;
    "cut": boolean;
}

/**
 * PickDirectoryInput 目录选择入参。
 * Title 为对话框标题;Default 为初始展开目录(可为空,由系统决定)。
 */
export interface PickDirectoryInput {
    "title"?: string;
    "default"?: string;
}

/**
 * PickDirectoryResult 目录选择结果。
 * Canceled=true 时 Path 为空,表示用户取消。
 */
export interface PickDirectoryResult {
    "path": string;
    "canceled": boolean;
}

/**
 * PromptTemplate 提示词模板持久化模型。
 */
export interface PromptTemplate {
    "id": number;
    "title": string;
    "content": string;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * ReadFileResult 读取文件结果。ModTime 为 Unix 秒,用于后续写入时的 data race 检测。
 */
export interface ReadFileResult {
    "path": string;
    "content": string;
    "size": number;
    "modTime": number;
}

/**
 * RecentItem 记录用户最近打开的目录或文件。
 */
export interface RecentItem {
    "id": number;
    "path": string;

    /**
     * "dir" | "file"
     */
    "kind": string;
    "openedAt": string;
}

/**
 * RemoveRecentInput 前端调用 Remove 的入参。
 */
export interface RemoveRecentInput {
    "id": number;
}

/**
 * RenameConversationInput 重命名会话入参。
 */
export interface RenameConversationInput {
    "conversationId": number;
    "title": string;
}

/**
 * RenameInput 同级重命名入参。NewName 只能是纯文件名,不能包含分隔符。
 */
export interface RenameInput {
    "path": string;
    "newName": string;
    "batchId"?: number;
}

/**
 * RenameResult 重命名结果。Renamed=false 表示新旧同名,已静默跳过。
 */
export interface RenameResult {
    "path": string;
    "oldPath": string;
    "renamed": boolean;
}

/**
 * SetAlwaysOnTopInput 前端调用 SetAlwaysOnTop 的入参。
 */
export interface SetAlwaysOnTopInput {
    "enabled": boolean;
}

/**
 * SetPinnedInput 置顶/取消置顶入参。
 */
export interface SetPinnedInput {
    "conversationId": number;
    "pinned": boolean;
}

/**
 * SetTemplatesInput 保存会话启用的模板集合。
 */
export interface SetTemplatesInput {
    "conversationId": number;
    "templateIds": number[] | null;
}

/**
 * SetWorkspaceRootInput 设置根目录入参。
 */
export interface SetWorkspaceRootInput {
    "root": string;
}

/**
 * TrayService 提供给前端主动切换到"系统托盘运行"模式的能力。
 * 
 * 前端调用 EnableTray 后:
 *   - 主窗口被隐藏(而非关闭);
 *   - 在系统托盘创建图标与菜单(Show / Quit);
 *   - 窗口关闭事件被拦截为"隐藏",保证再次通过托盘唤出。
 * 
 * DisableTray 会移除托盘并恢复窗口的默认关闭行为。
 * 
 * TrayService 不直接依赖 window 包,主窗口通过 SetWindow 由 app 层注入,
 * 避免 services -> window 的循环依赖。
 * TrayModePersister 持久化"当前是否处于托盘模式"偏好的回调。
 * 由 app 层注入,通常是 WindowService.SavePersistedTrayMode 的闭包,
 * 避免 TrayService 反向依赖 WindowService。
 */
export type TrayModePersister = any;

/**
 * UndoBatchResult 撤销结果概览。
 */
export interface UndoBatchResult {
    "batchId": number;
    "restoredPaths": string[] | null;
    "warnings": string[] | null;
}

/**
 * UpdateInput 修改入参。
 */
export interface UpdateInput {
    "id": number;
    "title": string;
    "content": string;
}

/**
 * UpdateMessageInput 修改消息正文入参。
 */
export interface UpdateMessageInput {
    "messageId": number;
    "content": string;
}

/**
 * WorkspaceEntry 目录树中的单项元数据。
 * 字段设计与 FileEntry 保持一致的命名风格,并增加 IsHidden / IsSymlink
 * 供前端做视觉区分。
 */
export interface WorkspaceEntry {
    "name": string;
    "path": string;
    "parent": string;
    "isDir": boolean;
    "isHidden": boolean;
    "isSymlink": boolean;
    "size": number;

    /**
     * Unix 秒
     */
    "modTime": number;
}

/**
 * WorkspaceRootInfo 工作区根目录状态。
 */
export interface WorkspaceRootInfo {
    "root": string;
    "exists": boolean;
    "watching": boolean;

    /**
     * fsnotify 不可用,已降级为轮询
     */
    "degraded": boolean;
    "reason"?: string;
}

/**
 * WriteFileInput 写文件入参。
 * 若目标目录不存在,自动创建父目录。
 * BatchID 可选:若非零,写盘前登记原始状态以支持后续撤销。
 * ExpectedModTime 可选(Unix 秒):若非零且目标文件已存在,写入前会比对磁盘上的 mtime,
 * 不一致则拒绝写入(data race 保护)。新建文件场景该字段被忽略。
 */
export interface WriteFileInput {
    "path": string;
    "content": string;
    "batchId"?: number;
    "expectedModTime"?: number;
}

/**
 * WriteFileResult 写文件结果,包含 git 风格的 diff 提示。
 * Created=true 表示新建文件(展示"创建文件"),否则展示"编辑文件"。
 */
export interface WriteFileResult {
    "path": string;
    "created": boolean;
    "diff": string;
}
