// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CreateInput 新建入参。
 */
export interface CreateInput {
    "title": string;
    "content": string;
}

/**
 * PromptTemplate 提示词模板持久化模型。
 */
export interface PromptTemplate {
    "id": number;
    "title": string;
    "content": string;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * UpdateInput 修改入参。
 */
export interface UpdateInput {
    "id": number;
    "title": string;
    "content": string;
}
