// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PromptTemplateService 提供提示词模板的增删改查能力,暴露给前端调用。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Create 新建模板。
 */
export function Create($in: $models.CreateInput): $CancellablePromise<$models.PromptTemplate | null> {
    return $Call.ByID(3093467241, $in);
}

/**
 * Delete 删除模板。
 */
export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByID(3789905310, id);
}

/**
 * List 列出全部模板,按更新时间倒序。
 */
export function List(): $CancellablePromise<$models.PromptTemplate[] | null> {
    return $Call.ByID(2315848229);
}

/**
 * Update 修改模板。
 */
export function Update($in: $models.UpdateInput): $CancellablePromise<$models.PromptTemplate | null> {
    return $Call.ByID(1469297912, $in);
}
