// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SnapshotService 负责文件修改批次的快照登记与撤销。
 * 与 FileService 之间的耦合通过 "同包内部方法" 实现:FileService 在实际写盘前
 * 调用 SnapshotService.recordIfNeeded 将原始内容登记为快照。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BeginBatch 开启一个空批次,返回 batchID。
 * MessageID 允许为 0(尚未落库),稍后调用 Bind 绑定。
 */
export function BeginBatch($in: $models.BeginBatchInput): $CancellablePromise<$models.BeginBatchResult | null> {
    return $Call.ByID(3189451666, $in);
}

/**
 * Bind 将批次关联到最终落库的 AI 消息 id。
 */
export function Bind($in: $models.BindBatchInput): $CancellablePromise<void> {
    return $Call.ByID(2359684614, $in);
}

/**
 * Status 查询一个批次的状态摘要;供前端渲染撤销入口。
 */
export function Status(batchID: number): $CancellablePromise<$models.BatchStatus | null> {
    return $Call.ByID(3418874023, batchID);
}

/**
 * Undo 撤销一个批次:将其中登记的所有路径回滚到批次开启前的状态。
 * 已撤销的批次再次调用将报错。
 */
export function Undo(batchID: number): $CancellablePromise<$models.UndoBatchResult | null> {
    return $Call.ByID(2149980391, batchID);
}
