// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DisableTray 关闭托盘模式,移除托盘图标并恢复窗口关闭默认行为,
 * 同时将主窗口重新显示出来。
 * 幂等:未启用时直接返回。
 */
export function DisableTray(): $CancellablePromise<void> {
    return $Call.ByID(1230576727);
}

/**
 * EnableTray 启用托盘模式:隐藏主窗口并创建托盘图标与菜单。
 * 幂等:重复调用不会重复创建。
 */
export function EnableTray(): $CancellablePromise<void> {
    return $Call.ByID(2173511770);
}

/**
 * IsTrayActive 返回当前是否处于托盘模式。
 */
export function IsTrayActive(): $CancellablePromise<boolean> {
    return $Call.ByID(1924291503);
}

/**
 * SetApp 由 app 层注入 Wails application 引用。
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(303054654, app);
}

/**
 * SetIcon 允许 app 层注入托盘图标数据(PNG 字节)。
 * 非 darwin 平台使用普通图标,darwin 使用 template 图标。
 * 未调用时使用 Wails 内置默认图标。
 */
export function SetIcon(data: string | null): $CancellablePromise<void> {
    return $Call.ByID(3452703594, data);
}

/**
 * SetPersister 注入托盘模式持久化回调。
 */
export function SetPersister(p: $models.TrayModePersister): $CancellablePromise<void> {
    return $Call.ByID(114291146, p);
}

/**
 * SetWindow 由 app 层注入主窗口引用。
 */
export function SetWindow(win: application$0.WebviewWindow | null): $CancellablePromise<void> {
    return $Call.ByID(1421440515, win);
}

/**
 * ShowWindow 主动显示并聚焦主窗口(供前端在托盘模式下唤出窗口)。
 */
export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(3299517208);
}
