// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TrayService 提供给前端主动切换到"系统托盘运行"模式的能力。
 * 
 * 前端调用 EnableTray 后:
 *   - 主窗口被隐藏(而非关闭);
 *   - 在系统托盘创建图标与菜单(Show / Quit);
 *   - 窗口关闭事件被拦截为"隐藏",保证再次通过托盘唤出。
 * 
 * DisableTray 会移除托盘并恢复窗口的默认关闭行为。
 * 
 * TrayService 不直接依赖 window 包,主窗口通过 SetWindow 由 app 层注入,
 * 避免 services -> window 的循环依赖。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * DisableTray 关闭托盘模式,移除托盘图标并恢复窗口关闭默认行为,
 * 同时将主窗口重新显示出来。
 * 幂等:未启用时直接返回。
 */
export function DisableTray(): $CancellablePromise<void> {
    return $Call.ByID(1230576727);
}

/**
 * EnableTray 启用托盘模式:隐藏主窗口并创建托盘图标与菜单。
 * 幂等:重复调用不会重复创建。
 */
export function EnableTray(): $CancellablePromise<void> {
    return $Call.ByID(2173511770);
}

/**
 * IsTrayActive 返回当前是否处于托盘模式。
 */
export function IsTrayActive(): $CancellablePromise<boolean> {
    return $Call.ByID(1924291503);
}

/**
 * SetApp 由 app 层注入 Wails application 引用。
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(303054654, app);
}

/**
 * SetIcon 允许 app 层注入托盘图标数据(PNG 字节)。
 * 非 darwin 平台使用普通图标,darwin 使用 template 图标。
 * 未调用时使用 Wails 内置默认图标。
 */
export function SetIcon(data: string | null): $CancellablePromise<void> {
    return $Call.ByID(3452703594, data);
}

/**
 * SetWindow 由 app 层注入主窗口引用。
 */
export function SetWindow(win: application$0.WebviewWindow | null): $CancellablePromise<void> {
    return $Call.ByID(1421440515, win);
}

/**
 * ShowWindow 主动显示并聚焦主窗口(供前端在托盘模式下唤出窗口)。
 */
export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(3299517208);
}
