// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService 管理主窗口的用户可持久化设置。
 * 目前实现:置顶状态 (Always On Top)。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAlwaysOnTop 返回当前置顶状态(内存缓存,与数据库保持同步)。
 */
export function GetAlwaysOnTop(): $CancellablePromise<$models.AlwaysOnTopState | null> {
    return $Call.ByID(4027921382);
}

/**
 * LoadPersistedAlwaysOnTop 从数据库读取上次保存的置顶状态。
 * 记录不存在时返回 false,不视为错误。app 层在创建窗口之前调用,
 * 以便用初始状态构造窗口。
 */
export function LoadPersistedAlwaysOnTop(): $CancellablePromise<boolean> {
    return $Call.ByID(2850600265);
}

/**
 * SetAlwaysOnTop 设置置顶状态,持久化并应用到窗口。
 * 成功后广播 WindowEventAlwaysOnTopChanged。
 */
export function SetAlwaysOnTop($in: $models.SetAlwaysOnTopInput): $CancellablePromise<$models.AlwaysOnTopState | null> {
    return $Call.ByID(1578897338, $in);
}

/**
 * SetEmitter 注入事件推送能力。
 */
export function SetEmitter(e: $models.Emitter): $CancellablePromise<void> {
    return $Call.ByID(1273247899, e);
}

/**
 * SetSetter 注入窗口置顶设置器。app 层在创建窗口后调用。
 */
export function SetSetter(setter: $models.AlwaysOnTopSetter): $CancellablePromise<void> {
    return $Call.ByID(1935862764, setter);
}

/**
 * ToggleAlwaysOnTop 翻转当前置顶状态。
 */
export function ToggleAlwaysOnTop(): $CancellablePromise<$models.AlwaysOnTopState | null> {
    return $Call.ByID(374554492);
}
