// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ClipboardService 提供跨平台的文件剪贴板写入能力。
 * 前端 Ctrl+C / Ctrl+X 时,除了在内存中(useClipboardStore)记录,
 * 还调用本服务把路径写入系统剪贴板,使用户可在系统文件管理器中直接 Ctrl+V 粘贴。
 * 
 * 说明:
 * - Windows 使用 PowerShell 的 Set-Clipboard -Path,产生 CF_HDROP 剪贴板格式,
 *   Explorer 会识别为"复制文件"操作(粘贴时即复制)。剪切语义受限于系统 API,
 *   这里统一按"复制"写入系统剪贴板;内部剪切语义仍由前端 store + 后端删除源实现。
 * - macOS 使用 osascript,把路径转换为 POSIX file 引用列表写入通用剪贴板。
 * - Linux 优先 wl-copy(Wayland),回退 xclip(X11),写入 text/uri-list MIME。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ReadPaths 从系统剪贴板读取文件路径列表。
 * 若剪贴板不含文件引用,返回空 Paths 和 nil 错误(调用方据此决定是否降级为文本粘贴)。
 * Cut 字段在支持的平台上反映"剪切"语义(目前 Windows 下通过 Preferred DropEffect 判定)。
 */
export function ReadPaths(): $CancellablePromise<$models.ClipboardPaths | null> {
    return $Call.ByID(3673925826);
}

/**
 * WritePaths 将给定的绝对路径集合写入系统剪贴板。
 * 所有路径必须为绝对路径且必须存在,否则返回错误。
 * 空列表视为参数错误。
 */
export function WritePaths(paths: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2662352507, paths);
}
