// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ClipboardPaths 表示从系统剪贴板读取到的文件路径集合及其操作语义。
 * Cut=true 表示系统剪贴板标记为"剪切"(Windows 下 Preferred DropEffect=2),
 * 粘贴方应在复制成功后删除源文件。
 */
export interface ClipboardPaths {
    "paths": string[] | null;
    "cut": boolean;
}
